### ISSUE TITLE
Group Bot

### ISSUE THREAD

**Issue by ervan0707** [GoogleX133/LINE-SquareBot#1]
can u create examples to create group bot with this lib?

**Comment by BroNils** [comment]
make a group bot ? not square bot ? ok i'll do it best

**Comment by ervan0707** [comment]
yea, cant wait for this

**Comment by BroNils** [comment]
Done ;) ..... => [Talk / Group Bot](https://github.com/GoogleX133/LINE-SquareBot/blob/master/examples/talk.js)

**Comment by BroNils** [comment]
Run with

```sh
$ node ./examples/talk.js
```

**Comment by ervan0707** [comment]
woahh thx dude for :D
