### ISSUE TITLE
TypeError: xthrift.sendMessage is not a function

### ISSUE THREAD

**Issue by ervan0707** [GoogleX133/LINE-SquareBot#2]
when i try talkSendMessage func, i got error like this TypeError: xthrift.sendMessage is not a function

i try with botlib.talkSendMessage(Tcustom.talk, receiver, 'string/text');

**Comment by BroNils** [comment]
Your code is wrong.... see ./pkg/main.js to understand it. 
Here is the example:

# talkSimpleSendMessage()
```javascript
botlib.talkSimpleSendMessage(Tcustom.talk, receiver, 'string/text');
```

# talkSendMessage()
```javascript
botlib.talkSendMessage((err,success)=>{
    #your code here
}, Tcustom.talk, 'string/text', receiver.to, '', 0)
```
or
```javascript
botlib.talkSendMessage('', Tcustom.talk, 'string/text', receiver.to, '', 0)
```

# information
- Tcustom.talk (is a thrift)
- receiver (is a TTypes.Message() class)
