### ISSUE TITLE
more examples talk function

### ISSUE THREAD

**Issue by frisgajohan** [GoogleX133/LINE-SquareBot#3]
can you create more examples for talk? like getgroup, get contacts or something
i try create  
getContacts: function(xthrift, mid) {
        return xthrift.getContacts(mid)
    },
but the output is just {}

**Comment by BroNils** [comment]
ok i will make one for you. but i don't know when it's done

**Comment by BroNils** [comment]
the output {} is because you didn't wait for the result / callback. This is javascipt man, not like php javascript is sucks, you must use async or any callback trigger to get the result before you do the next script

**Comment by BroNils** [comment]
here is the right one:
```javascript
getContacts: function(xthrift, mid, callback){
    xthrift.getContacts(mid,(err,success)=>{
        if(module.exports.isFunction(callback)){
            callback(err,success)
        }else{
            return success
        }
    })
}
```

here is how you call getContacts (with callback)
```javascript
botlib.getContacts(Tcustom.talk,mid,(err,success)=>{
    if(err) throw err
    console.info(success)
})
```
her is how you call getContacts (with no callback)
```javascript
botlib.getContacts(Tcustom.talk,mid)
```

**Comment by BroNils** [comment]
soon i will make more talk API on main.js

**Comment by frisgajohan** [comment]
oke thanks dude cant wait for this

**Comment by frisgajohan** [comment]
![image](https://user-images.githubusercontent.com/36871574/36806616-2509c080-1cf3-11e8-9302-0e51f2cf5478.png)

get new problem, i try with
`botlib.getContacts(Tcustom.talk,sender,(err,success)=>{
                if(err) throw err
                    console.info(success)
            })`
the output just [], how i can get mid, displayName and others? sorry i new in nodejs

**Comment by BroNils** [comment]
Here correction:
```javascript
botlib.getContacts(Tcustom.talk,[mid],(err,success)=>{
    if(err) throw err
    console.info(success)
})
```
*Mid must be an array, because the thrift you are calling is getContacts (mean more than 1 mid)

> Sorry my bad

**Comment by BroNils** [comment]
DONE !!!, New Update for botlib / main.js !!.
>See changelog [here](https://github.com/GoogleX133/LINE-SquareBot/commit/26b407db1744c54de5542e32f4d161b342214aa7)
